version: '3'

services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    # Note: Remove the depends_on for mongo if not using local mongo.

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

