version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
     # - "53:53/tcp"
     # - "53:53/udp"
     # - "67:67/udp"
     # - "80:80/tcp"
     # - "443:443/tcp"
      - "8080:80/tcp"
    environment:
      TZ: 'America/Los_Angeles'
      WEBPASSWORD: 'USFf1W1s11'
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    restart: unless-stopped
