/**
 * sampleJobs.js — a built-in set of realistic job listings.
 *
 * This replaces the external RapidAPI call so the app works instantly with no
 * API key, no quota, and no network errors. The /recommendations endpoint
 * filters these by the user's desired position and location when possible.
 *
 * To go back to a live API later, swap this out in server.js.
 */

const SAMPLE_JOBS = [
  {
    title: 'Senior Frontend Engineer',
    company: 'Stripe',
    location: 'San Francisco, CA',
    description: 'Build delightful, high-performance payment experiences with React and TypeScript alongside a world-class design team.',
    datePosted: '2 days ago',
    employmentType: 'Full-time',
    image: '',
    tags: ['frontend', 'react', 'engineer', 'developer', 'web'],
    jobProviders: [
      { jobProvider: 'LinkedIn', url: 'https://www.linkedin.com/jobs/' },
      { jobProvider: 'Indeed', url: 'https://www.indeed.com/' },
    ],
  },
  {
    title: 'Full Stack Developer',
    company: 'Notion',
    location: 'Remote',
    description: 'Own features end to end across our web app and API. Work with Node, Postgres, and React to ship at a fast pace.',
    datePosted: '4 days ago',
    employmentType: 'Full-time',
    image: '',
    tags: ['full stack', 'developer', 'node', 'react', 'web', 'engineer'],
    jobProviders: [{ jobProvider: 'Greenhouse', url: 'https://www.greenhouse.io/' }],
  },
  {
    title: 'Backend Engineer',
    company: 'Vercel',
    location: 'Remote',
    description: 'Scale the platform that powers the modern web. Strong experience with Go, Rust, or Node and distributed systems.',
    datePosted: '1 week ago',
    employmentType: 'Contract',
    image: '',
    tags: ['backend', 'engineer', 'developer', 'go', 'node'],
    jobProviders: [{ jobProvider: 'AngelList', url: 'https://wellfound.com/' }],
  },
  {
    title: 'Product Designer',
    company: 'Figma',
    location: 'New York, NY',
    description: 'Shape the tools millions of designers use every day. Lead design for core product surfaces from concept to ship.',
    datePosted: '3 days ago',
    employmentType: 'Full-time',
    image: '',
    tags: ['designer', 'product', 'ux', 'ui', 'design'],
    jobProviders: [{ jobProvider: 'Lever', url: 'https://www.lever.co/' }],
  },
  {
    title: 'UX/UI Designer',
    company: 'Airbnb',
    location: 'Remote',
    description: 'Craft intuitive, beautiful interfaces for our guest and host experiences. Strong portfolio in mobile and web.',
    datePosted: '5 days ago',
    employmentType: 'Full-time',
    image: '',
    tags: ['designer', 'ux', 'ui', 'design', 'product'],
    jobProviders: [{ jobProvider: 'LinkedIn', url: 'https://www.linkedin.com/jobs/' }],
  },
  {
    title: 'Data Scientist',
    company: 'Spotify',
    location: 'Boston, MA',
    description: 'Turn listening data into product insights. Build models that power recommendations for hundreds of millions of users.',
    datePosted: '6 days ago',
    employmentType: 'Full-time',
    image: '',
    tags: ['data', 'scientist', 'analyst', 'machine learning', 'python'],
    jobProviders: [{ jobProvider: 'Indeed', url: 'https://www.indeed.com/' }],
  },
  {
    title: 'Data Analyst',
    company: 'Shopify',
    location: 'Remote',
    description: 'Partner with product and ops teams to answer key business questions using SQL, dashboards, and clear storytelling.',
    datePosted: '1 week ago',
    employmentType: 'Full-time',
    image: '',
    tags: ['data', 'analyst', 'sql', 'analytics'],
    jobProviders: [{ jobProvider: 'Greenhouse', url: 'https://www.greenhouse.io/' }],
  },
  {
    title: 'DevOps Engineer',
    company: 'Datadog',
    location: 'Denver, CO',
    description: 'Own CI/CD and cloud infrastructure across AWS and Kubernetes. Improve reliability and developer velocity.',
    datePosted: '2 days ago',
    employmentType: 'Full-time',
    image: '',
    tags: ['devops', 'engineer', 'aws', 'kubernetes', 'infrastructure'],
    jobProviders: [{ jobProvider: 'LinkedIn', url: 'https://www.linkedin.com/jobs/' }],
  },
  {
    title: 'Mobile Developer (iOS)',
    company: 'Robinhood',
    location: 'Menlo Park, CA',
    description: 'Build the iOS app used by millions to invest. Swift, SwiftUI, and a passion for polished mobile experiences.',
    datePosted: '4 days ago',
    employmentType: 'Full-time',
    image: '',
    tags: ['mobile', 'developer', 'ios', 'swift', 'engineer'],
    jobProviders: [{ jobProvider: 'Lever', url: 'https://www.lever.co/' }],
  },
  {
    title: 'Product Manager',
    company: 'Linear',
    location: 'Remote',
    description: 'Define and ship features that developers love. Work closely with design and engineering on a fast-moving roadmap.',
    datePosted: '3 days ago',
    employmentType: 'Full-time',
    image: '',
    tags: ['product', 'manager', 'pm', 'strategy'],
    jobProviders: [{ jobProvider: 'AngelList', url: 'https://wellfound.com/' }],
  },
  {
    title: 'Machine Learning Engineer',
    company: 'OpenAI',
    location: 'San Francisco, CA',
    description: 'Train and deploy large-scale models in production. Strong Python and deep learning fundamentals required.',
    datePosted: '1 day ago',
    employmentType: 'Full-time',
    image: '',
    tags: ['machine learning', 'ml', 'engineer', 'ai', 'python', 'data'],
    jobProviders: [{ jobProvider: 'LinkedIn', url: 'https://www.linkedin.com/jobs/' }],
  },
  {
    title: 'QA Engineer',
    company: 'Atlassian',
    location: 'Austin, TX',
    description: 'Design test plans and automation to keep our products rock solid. Experience with Cypress or Playwright a plus.',
    datePosted: '5 days ago',
    employmentType: 'Full-time',
    image: '',
    tags: ['qa', 'engineer', 'testing', 'automation'],
    jobProviders: [{ jobProvider: 'Indeed', url: 'https://www.indeed.com/' }],
  },
  {
    title: 'Junior Web Developer',
    company: 'Squarespace',
    location: 'New York, NY',
    description: 'Great first role for an early-career developer. Build and maintain customer-facing site features with JavaScript.',
    datePosted: '2 days ago',
    employmentType: 'Full-time',
    image: '',
    tags: ['web', 'developer', 'junior', 'frontend', 'javascript', 'engineer'],
    jobProviders: [{ jobProvider: 'Greenhouse', url: 'https://www.greenhouse.io/' }],
  },
  {
    title: 'Software Engineer Intern',
    company: 'Google',
    location: 'Mountain View, CA',
    description: 'Summer internship working on real projects with a mentor. Open to current CS students with strong fundamentals.',
    datePosted: '1 week ago',
    employmentType: 'Internship',
    image: '',
    tags: ['software', 'engineer', 'intern', 'developer'],
    jobProviders: [{ jobProvider: 'LinkedIn', url: 'https://www.linkedin.com/jobs/' }],
  },
  {
    title: 'Cloud Solutions Architect',
    company: 'Microsoft',
    location: 'Seattle, WA',
    description: 'Help enterprise customers design and migrate workloads to Azure. Blend of technical depth and customer skills.',
    datePosted: '6 days ago',
    employmentType: 'Full-time',
    image: '',
    tags: ['cloud', 'architect', 'azure', 'engineer', 'infrastructure'],
    jobProviders: [{ jobProvider: 'Indeed', url: 'https://www.indeed.com/' }],
  },
  {
    title: 'Frontend Developer',
    company: 'GitHub',
    location: 'Remote',
    description: 'Build accessible, fast UI for tools used by millions of developers. Deep React and CSS expertise valued.',
    datePosted: '3 days ago',
    employmentType: 'Full-time',
    image: '',
    tags: ['frontend', 'developer', 'react', 'web', 'engineer', 'css'],
    jobProviders: [{ jobProvider: 'Lever', url: 'https://www.lever.co/' }],
  },
];

module.exports = SAMPLE_JOBS;
