apiVersion: v1
kind: Secret
metadata:
  name: datadog-secret
type: Opaque
data:
  api-key: MzVjYWQzZWMwYzIwZTYwNzI0ZmI1MWNhMGFhM2JhNDY2YzcyMjBlYg==
  app-key: MjNkMDNlMTUtOWNmOC00YWNiLTgwMDctNzExODBlMDhlYTNm 
