version: '3.8'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx_tls
    volumes:
      - ./selfsigned.crt:/etc/nginx/ssl/selfsigned.crt
      - ./priv.key:/etc/nginx/ssl/priv.key
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "443:443"
    restart: unless-stopped
